# Generated by Django 3.1.3 on 2021-02-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True, primary_key=True, serialize=False)),
                ('endpoint_name', models.CharField(max_length=50)),
                ('call_params', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
            ],
        ),
    ]
